/**
 * Generate comprehensive clinical-vocabulary.json from in-code definitions.
 * Run: npx tsx scripts/generate-vocabulary.ts
 */
import * as fs from "fs";
import * as path from "path";

interface Entry {
  term: string;
  abbreviations: string[];
  body_system: string;
  vindicate_category: string;
}

function e(term: string, abbr: string[], sys: string, vc: string): Entry {
  return { term, abbreviations: abbr, body_system: sys, vindicate_category: vc };
}

const entries: Entry[] = [
  // ===== CARDIOVASCULAR =====
  e("Acute Coronary Syndrome", ["ACS", "MI", "heart attack", "NSTEMI", "STEMI"], "Cardiovascular", "V"),
  e("Myocardial Infarction", ["MI", "heart attack", "STEMI", "NSTEMI"], "Cardiovascular", "V"),
  e("Unstable Angina", ["UA"], "Cardiovascular", "V"),
  e("Stable Angina", [], "Cardiovascular", "V"),
  e("Aortic Dissection", ["dissection"], "Cardiovascular", "V"),
  e("Deep Vein Thrombosis", ["DVT"], "Cardiovascular", "V"),
  e("Atrial Fibrillation", ["AFib", "AF"], "Cardiovascular", "V"),
  e("Heart Failure", ["CHF", "HF", "congestive"], "Cardiovascular", "V"),
  e("Acute Pericarditis", ["pericarditis", "viral pericarditis"], "Cardiovascular", "I"),
  e("Myocarditis", [], "Cardiovascular", "I"),
  e("Cardiac Tamponade", ["tamponade"], "Cardiovascular", "V"),
  e("Aortic Stenosis", ["AS"], "Cardiovascular", "D"),
  e("Hypertensive Emergency", ["HTN emergency"], "Cardiovascular", "V"),
  e("Stroke", ["CVA", "cerebrovascular accident"], "Cardiovascular", "V"),
  e("Transient Ischemic Attack", ["TIA"], "Cardiovascular", "V"),
  e("Peripheral Arterial Disease", ["PAD", "PVD"], "Cardiovascular", "V"),
  e("Mitral Valve Prolapse", ["MVP"], "Cardiovascular", "C"),
  e("Mitral Stenosis", ["MS"], "Cardiovascular", "D"),
  e("Mitral Regurgitation", ["MR"], "Cardiovascular", "D"),
  e("Aortic Regurgitation", ["AR", "AI"], "Cardiovascular", "D"),
  e("Tricuspid Regurgitation", ["TR"], "Cardiovascular", "D"),
  e("Wolff-Parkinson-White Syndrome", ["WPW"], "Cardiovascular", "C"),
  e("Supraventricular Tachycardia", ["SVT", "PSVT"], "Cardiovascular", "V"),
  e("Ventricular Tachycardia", ["VT", "V-tach"], "Cardiovascular", "V"),
  e("Ventricular Fibrillation", ["VF", "V-fib"], "Cardiovascular", "V"),
  e("Sinus Bradycardia", ["bradycardia"], "Cardiovascular", "V"),
  e("Sick Sinus Syndrome", ["SSS"], "Cardiovascular", "D"),
  e("Atrioventricular Block", ["AV block", "heart block"], "Cardiovascular", "D"),
  e("Bundle Branch Block", ["BBB", "LBBB", "RBBB"], "Cardiovascular", "D"),
  e("Long QT Syndrome", ["LQTS"], "Cardiovascular", "C"),
  e("Brugada Syndrome", [], "Cardiovascular", "C"),
  e("Dilated Cardiomyopathy", ["DCM"], "Cardiovascular", "D"),
  e("Hypertrophic Cardiomyopathy", ["HCM", "HOCM"], "Cardiovascular", "C"),
  e("Restrictive Cardiomyopathy", ["RCM"], "Cardiovascular", "D"),
  e("Infective Endocarditis", ["IE", "endocarditis"], "Cardiovascular", "I"),
  e("Libman-Sacks Endocarditis", [], "Cardiovascular", "A"),
  e("Rheumatic Heart Disease", ["RHD"], "Cardiovascular", "A"),
  e("Cor Pulmonale", [], "Cardiovascular", "V"),
  e("Patent Ductus Arteriosus", ["PDA"], "Cardiovascular", "C"),
  e("Ventricular Septal Defect", ["VSD"], "Cardiovascular", "C"),
  e("Atrial Septal Defect", ["ASD"], "Cardiovascular", "C"),
  e("Tetralogy of Fallot", ["TOF"], "Cardiovascular", "C"),
  e("Coarctation of the Aorta", ["CoA"], "Cardiovascular", "C"),
  e("Aortic Aneurysm", ["AAA"], "Cardiovascular", "V"),
  e("Thoracic Aortic Aneurysm", ["TAA"], "Cardiovascular", "V"),
  e("Abdominal Aortic Aneurysm", ["AAA"], "Cardiovascular", "V"),
  e("Pericardial Effusion", [], "Cardiovascular", "V"),
  e("Constrictive Pericarditis", [], "Cardiovascular", "I"),
  e("Dressler Syndrome", ["post-MI pericarditis"], "Cardiovascular", "A"),
  e("Orthostatic Hypotension", [], "Cardiovascular", "V"),
  e("Hypertension", ["HTN", "high blood pressure"], "Cardiovascular", "V"),
  e("Pulmonary Hypertension", ["PAH", "PH"], "Cardiovascular", "V"),
  e("Coronary Artery Disease", ["CAD"], "Cardiovascular", "V"),
  e("Acute Limb Ischemia", ["ALI"], "Cardiovascular", "V"),
  e("Claudication", ["intermittent claudication"], "Cardiovascular", "V"),
  e("Superior Vena Cava Syndrome", ["SVC syndrome"], "Cardiovascular", "N"),
  e("Subclavian Steal Syndrome", [], "Cardiovascular", "V"),
  e("Budd-Chiari Syndrome", [], "Cardiovascular", "V"),
  e("Portal Hypertension", [], "Cardiovascular", "V"),
  e("Takotsubo Cardiomyopathy", ["broken heart syndrome", "stress cardiomyopathy"], "Cardiovascular", "V"),
  e("Raynaud Phenomenon", ["Raynaud's"], "Cardiovascular", "V"),
  e("Vasovagal Syncope", ["neurocardiogenic syncope"], "Cardiovascular", "V"),
  e("Arrhythmogenic Right Ventricular Cardiomyopathy", ["ARVC"], "Cardiovascular", "C"),
  e("Atrial Myxoma", [], "Cardiovascular", "N"),
  e("Paroxysmal Atrial Fibrillation", ["PAF"], "Cardiovascular", "V"),

  // ===== PULMONARY =====
  e("Pulmonary Embolism", ["PE"], "Pulmonary", "V"),
  e("Pneumonia", ["PNA", "CAP", "community acquired pneumonia"], "Pulmonary", "I"),
  e("Pneumothorax", ["PTX", "collapsed lung"], "Pulmonary", "T"),
  e("Tension Pneumothorax", ["tension PTX"], "Pulmonary", "T"),
  e("Asthma Exacerbation", ["asthma"], "Pulmonary", "A"),
  e("COPD Exacerbation", ["COPD", "AECOPD"], "Pulmonary", "D"),
  e("Pleural Effusion", ["effusion"], "Pulmonary", "V"),
  e("Pulmonary Edema", [], "Pulmonary", "V"),
  e("Acute Respiratory Distress Syndrome", ["ARDS"], "Pulmonary", "T"),
  e("Pulmonary Fibrosis", ["IPF"], "Pulmonary", "D"),
  e("Idiopathic Pulmonary Fibrosis", ["IPF"], "Pulmonary", "D"),
  e("Lung Abscess", [], "Pulmonary", "I"),
  e("Empyema", [], "Pulmonary", "I"),
  e("Hemothorax", [], "Pulmonary", "T"),
  e("Chylothorax", [], "Pulmonary", "V"),
  e("Flail Chest", [], "Pulmonary", "T"),
  e("Pulmonary Contusion", [], "Pulmonary", "T"),
  e("Aspiration Pneumonia", [], "Pulmonary", "I"),
  e("Hospital-Acquired Pneumonia", ["HAP"], "Pulmonary", "I"),
  e("Ventilator-Associated Pneumonia", ["VAP"], "Pulmonary", "I"),
  e("Tuberculosis", ["TB"], "Pulmonary", "I"),
  e("Aspergillosis", [], "Pulmonary", "I"),
  e("Pneumocystis Pneumonia", ["PCP", "PJP"], "Pulmonary", "I"),
  e("Pulmonary Sarcoidosis", ["sarcoidosis"], "Pulmonary", "A"),
  e("Hypersensitivity Pneumonitis", ["HP"], "Pulmonary", "A"),
  e("Asbestosis", [], "Pulmonary", "T"),
  e("Silicosis", [], "Pulmonary", "T"),
  e("Mesothelioma", [], "Pulmonary", "N"),
  e("Obstructive Sleep Apnea", ["OSA"], "Pulmonary", "D"),
  e("Central Sleep Apnea", ["CSA"], "Pulmonary", "D"),
  e("Respiratory Failure", [], "Pulmonary", "V"),
  e("Acute Bronchitis", ["bronchitis"], "Pulmonary", "I"),
  e("Bronchiolitis", [], "Pulmonary", "I"),
  e("Bronchiectasis", [], "Pulmonary", "D"),
  e("Chronic Obstructive Pulmonary Disease", ["COPD"], "Pulmonary", "D"),
  e("Asthma", [], "Pulmonary", "A"),
  e("Croup", ["laryngotracheobronchitis"], "Pulmonary", "I"),
  e("Epiglottitis", [], "Pulmonary", "I"),
  e("Pertussis", ["whooping cough"], "Pulmonary", "I"),
  e("Foreign Body Aspiration", [], "Pulmonary", "T"),
  e("Goodpasture Syndrome", ["anti-GBM disease"], "Pulmonary", "A"),
  e("Chronic Eosinophilic Pneumonia", [], "Pulmonary", "A"),
  e("Lung Cancer", [], "Pulmonary", "N"),
  e("Pulmonary Alveolar Proteinosis", ["PAP"], "Pulmonary", "A"),
  e("Respiratory Distress Syndrome", ["RDS", "ARDS"], "Pulmonary", "T"),

  // ===== GASTROINTESTINAL =====
  e("Appendicitis", ["appy"], "Gastrointestinal", "I"),
  e("Acute Cholecystitis", ["cholecystitis", "gallbladder inflammation", "gallbladder infection"], "Gastrointestinal", "I"),
  e("Cholelithiasis", ["gallstones"], "Gastrointestinal", "E"),
  e("Choledocholithiasis with Cholangitis", ["cholangitis", "CBD stone", "common bile duct stone", "ascending cholangitis", "Charcot triad"], "Gastrointestinal", "I"),
  e("Biliary Pancreatitis", ["gallstone pancreatitis"], "Gastrointestinal", "I"),
  e("Pancreatitis", ["acute pancreatitis"], "Gastrointestinal", "I"),
  e("Biliary Colic", ["gallstone pain"], "Gastrointestinal", "E"),
  e("Small Bowel Obstruction", ["SBO", "bowel obstruction"], "Gastrointestinal", "T"),
  e("Gastroesophageal Reflux Disease", ["GERD", "acid reflux", "reflux"], "Gastrointestinal", "D"),
  e("Peptic Ulcer Disease", ["PUD", "ulcer", "gastric ulcer", "duodenal ulcer"], "Gastrointestinal", "I"),
  e("Diverticulitis", [], "Gastrointestinal", "I"),
  e("Inflammatory Bowel Disease", ["IBD", "Crohn's", "ulcerative colitis", "UC"], "Gastrointestinal", "A"),
  e("GI Bleed", ["GIB", "upper GI bleed", "lower GI bleed", "UGIB", "LGIB"], "Gastrointestinal", "V"),
  e("Gastritis", ["stomach inflammation"], "Gastrointestinal", "I"),
  e("Mesenteric Ischemia", ["intestinal ischemia"], "Gastrointestinal", "V"),
  e("Hepatitis", [], "Gastrointestinal", "I"),
  e("Cirrhosis", [], "Gastrointestinal", "D"),
  e("Achalasia", [], "Gastrointestinal", "D"),
  e("Esophageal Cancer", [], "Gastrointestinal", "N"),
  e("Barrett Esophagus", ["Barrett's"], "Gastrointestinal", "D"),
  e("Mallory-Weiss Tear", ["MW tear"], "Gastrointestinal", "T"),
  e("Boerhaave Syndrome", ["esophageal rupture", "esophageal perforation"], "Gastrointestinal", "T"),
  e("Esophageal Varices", [], "Gastrointestinal", "V"),
  e("Zenker Diverticulum", [], "Gastrointestinal", "D"),
  e("Eosinophilic Esophagitis", ["EoE"], "Gastrointestinal", "A"),
  e("Gastroparesis", [], "Gastrointestinal", "D"),
  e("Gastric Cancer", ["stomach cancer"], "Gastrointestinal", "N"),
  e("Gastric Outlet Obstruction", ["GOO"], "Gastrointestinal", "N"),
  e("Celiac Disease", ["celiac sprue", "gluten sensitivity"], "Gastrointestinal", "A"),
  e("Whipple Disease", [], "Gastrointestinal", "I"),
  e("Carcinoid Tumor", ["carcinoid"], "Gastrointestinal", "N"),
  e("Meckel Diverticulum", [], "Gastrointestinal", "C"),
  e("Intussusception", [], "Gastrointestinal", "V"),
  e("Volvulus", ["sigmoid volvulus", "cecal volvulus"], "Gastrointestinal", "T"),
  e("Toxic Megacolon", [], "Gastrointestinal", "I"),
  e("Ischemic Colitis", [], "Gastrointestinal", "V"),
  e("Pseudomembranous Colitis", ["C. diff colitis"], "Gastrointestinal", "I"),
  e("Colorectal Cancer", ["colon cancer", "CRC"], "Gastrointestinal", "N"),
  e("Anal Fissure", [], "Gastrointestinal", "T"),
  e("Perianal Abscess", [], "Gastrointestinal", "I"),
  e("Intestinal Perforation", [], "Gastrointestinal", "T"),
  e("Peritonitis", [], "Gastrointestinal", "I"),
  e("Spontaneous Bacterial Peritonitis", ["SBP"], "Gastrointestinal", "I"),
  e("Ascites", [], "Gastrointestinal", "V"),
  e("Hepatocellular Carcinoma", ["HCC", "liver cancer"], "Gastrointestinal", "N"),
  e("Hepatic Abscess", ["liver abscess"], "Gastrointestinal", "I"),
  e("Wilson Disease", [], "Gastrointestinal", "C"),
  e("Hemochromatosis", [], "Gastrointestinal", "C"),
  e("Alpha-1 Antitrypsin Deficiency", ["A1AT deficiency"], "Gastrointestinal", "C"),
  e("Primary Biliary Cholangitis", ["PBC", "primary biliary cirrhosis"], "Gastrointestinal", "A"),
  e("Autoimmune Hepatitis", ["AIH"], "Gastrointestinal", "A"),
  e("Nonalcoholic Fatty Liver Disease", ["NAFLD", "NASH"], "Gastrointestinal", "E"),
  e("Alcoholic Liver Disease", ["alcoholic hepatitis"], "Gastrointestinal", "I2"),
  e("Cholangiocarcinoma", ["bile duct cancer"], "Gastrointestinal", "N"),
  e("Chronic Pancreatitis", [], "Gastrointestinal", "D"),
  e("Pancreatic Adenocarcinoma", ["pancreatic cancer"], "Gastrointestinal", "N"),
  e("Zollinger-Ellison Syndrome", ["gastrinoma"], "Gastrointestinal", "N"),
  e("Crohn's Disease", ["Crohn's"], "Gastrointestinal", "A"),
  e("Ulcerative Colitis", ["UC"], "Gastrointestinal", "A"),
  e("C. Difficile Colitis", ["C. diff", "CDI"], "Gastrointestinal", "I"),
  e("Primary Sclerosing Cholangitis", ["PSC"], "Gastrointestinal", "A"),
  e("Hemorrhoids", [], "Gastrointestinal", "V"),
  e("Irritable Bowel Syndrome", ["IBS"], "Gastrointestinal", "D"),
  e("Ogilvie Syndrome", ["colonic pseudo-obstruction"], "Gastrointestinal", "V"),
  e("Dumping Syndrome", [], "Gastrointestinal", "I2"),
  e("Gastrointestinal Amyloidosis", [], "Gastrointestinal", "D"),
  e("Biliary Atresia", [], "Gastrointestinal", "C"),
  e("Duodenal Atresia", [], "Gastrointestinal", "C"),
  e("Acute Hepatitis B", ["HBV"], "Gastrointestinal", "I"),
  e("Fulminant Hepatic Failure", ["acute liver failure"], "Gastrointestinal", "I"),

  // ===== MUSCULOSKELETAL =====
  e("Costochondritis", ["costo"], "Musculoskeletal", "I"),
  e("Musculoskeletal Pain", ["MSK pain", "muscle strain"], "Musculoskeletal", "T"),
  e("Rib Fracture", [], "Musculoskeletal", "T"),
  e("Rib Contusion", ["chest wall injury", "chest wall contusion", "rib injury"], "Musculoskeletal", "T"),
  e("Lumbar Disc Herniation", ["disc herniation", "herniated disc", "HNP", "sciatica", "radiculopathy", "L4-L5 herniation", "L5-S1 herniation", "slipped disc"], "Musculoskeletal", "D"),
  e("Spinal Stenosis", [], "Musculoskeletal", "D"),
  e("Cauda Equina Syndrome", ["cauda equina", "CES"], "Musculoskeletal", "T"),
  e("Osteoarthritis", ["OA"], "Musculoskeletal", "D"),
  e("Piriformis Syndrome", ["piriformis", "deep gluteal syndrome"], "Musculoskeletal", "D"),
  e("Mechanical Low Back Pain", ["muscle strain", "lumbar strain", "back strain", "musculoskeletal back pain"], "Musculoskeletal", "T"),
  e("Spondylolisthesis", ["vertebral slip", "spondy"], "Musculoskeletal", "D"),
  e("Vertebral Compression Fracture", ["compression fracture", "VCF", "spinal fracture"], "Musculoskeletal", "T"),
  e("Vertebral Osteomyelitis", ["discitis", "spinal osteomyelitis", "vertebral infection"], "Musculoskeletal", "I"),
  e("Spinal Tumor/Metastasis", ["spinal tumor", "metastatic spine disease", "vertebral metastasis", "metastatic spinal lesion"], "Musculoskeletal", "N"),
  e("Rheumatoid Arthritis", ["RA"], "Musculoskeletal", "A"),
  e("Gout", ["gouty arthritis", "podagra"], "Musculoskeletal", "E"),
  e("Pseudogout", ["CPPD", "calcium pyrophosphate"], "Musculoskeletal", "E"),
  e("Septic Arthritis", ["infectious arthritis"], "Musculoskeletal", "I"),
  e("Bursitis", [], "Musculoskeletal", "T"),
  e("Tendinitis", ["tendonitis"], "Musculoskeletal", "T"),
  e("Rotator Cuff Tear", ["RCT"], "Musculoskeletal", "T"),
  e("Adhesive Capsulitis", ["frozen shoulder"], "Musculoskeletal", "D"),
  e("Lateral Epicondylitis", ["tennis elbow"], "Musculoskeletal", "T"),
  e("Medial Epicondylitis", ["golfer's elbow"], "Musculoskeletal", "T"),
  e("Carpal Tunnel Syndrome", ["CTS"], "Musculoskeletal", "D"),
  e("De Quervain Tenosynovitis", [], "Musculoskeletal", "T"),
  e("Plantar Fasciitis", [], "Musculoskeletal", "D"),
  e("Achilles Tendinitis", ["Achilles tendinopathy"], "Musculoskeletal", "T"),
  e("ACL Tear", ["anterior cruciate ligament tear"], "Musculoskeletal", "T"),
  e("Meniscus Tear", [], "Musculoskeletal", "T"),
  e("Baker Cyst", ["popliteal cyst"], "Musculoskeletal", "D"),
  e("Stress Fracture", [], "Musculoskeletal", "T"),
  e("Pathologic Fracture", [], "Musculoskeletal", "N"),
  e("Osteosarcoma", [], "Musculoskeletal", "N"),
  e("Hip Fracture", ["femoral neck fracture"], "Musculoskeletal", "T"),
  e("Slipped Capital Femoral Epiphysis", ["SCFE"], "Musculoskeletal", "D"),
  e("Legg-Calve-Perthes Disease", ["Perthes"], "Musculoskeletal", "V"),
  e("Osgood-Schlatter Disease", [], "Musculoskeletal", "D"),
  e("Ankylosing Spondylitis", ["AS"], "Musculoskeletal", "A"),
  e("Spinal Cord Compression", [], "Musculoskeletal", "N"),
  e("Compartment Syndrome", [], "Musculoskeletal", "T"),
  e("Rhabdomyolysis", ["rhabdo"], "Musculoskeletal", "T"),
  e("Fibromyalgia", ["fibro"], "Musculoskeletal", "D"),
  e("Polymyalgia Rheumatica", ["PMR"], "Musculoskeletal", "A"),
  e("Paget Disease of Bone", [], "Musculoskeletal", "D"),
  e("Osteoporosis", [], "Musculoskeletal", "E"),
  e("Osteomalacia", ["rickets"], "Musculoskeletal", "E"),
  e("Avascular Necrosis", ["AVN", "osteonecrosis"], "Musculoskeletal", "V"),
  e("Disc Herniation", ["herniated disc"], "Musculoskeletal", "D"),
  e("Dupuytren Contracture", [], "Musculoskeletal", "D"),
  e("Ganglion Cyst", [], "Musculoskeletal", "D"),
  e("Ewing Sarcoma", [], "Musculoskeletal", "N"),

  // ===== NEUROLOGICAL =====
  e("Migraine", [], "Neurological", "V"),
  e("Tension Headache", ["tension-type headache"], "Neurological", "D"),
  e("Cluster Headache", [], "Neurological", "V"),
  e("Meningitis", [], "Neurological", "I"),
  e("Subarachnoid Hemorrhage", ["SAH"], "Neurological", "V"),
  e("Epidural Abscess", [], "Neurological", "I"),
  e("Multiple Sclerosis", ["MS"], "Neurological", "A"),
  e("Ischemic Stroke", ["CVA", "cerebral infarction"], "Neurological", "V"),
  e("Hemorrhagic Stroke", ["ICH"], "Neurological", "V"),
  e("Intracerebral Hemorrhage", ["ICH"], "Neurological", "V"),
  e("Subdural Hematoma", ["SDH"], "Neurological", "T"),
  e("Epidural Hematoma", ["EDH"], "Neurological", "T"),
  e("Concussion", ["mild TBI"], "Neurological", "T"),
  e("Traumatic Brain Injury", ["TBI"], "Neurological", "T"),
  e("Seizure", ["convulsion"], "Neurological", "V"),
  e("Status Epilepticus", ["SE"], "Neurological", "V"),
  e("Guillain-Barre Syndrome", ["GBS"], "Neurological", "A"),
  e("Myasthenia Gravis", ["MG"], "Neurological", "A"),
  e("Lambert-Eaton Syndrome", ["LEMS"], "Neurological", "N"),
  e("Amyotrophic Lateral Sclerosis", ["ALS", "Lou Gehrig disease"], "Neurological", "D"),
  e("Alzheimer Disease", ["AD", "Alzheimer's"], "Neurological", "D"),
  e("Vascular Dementia", [], "Neurological", "V"),
  e("Frontotemporal Dementia", ["FTD"], "Neurological", "D"),
  e("Lewy Body Dementia", ["DLB"], "Neurological", "D"),
  e("Parkinson Disease", ["PD", "Parkinson's"], "Neurological", "D"),
  e("Huntington Disease", ["HD"], "Neurological", "C"),
  e("Essential Tremor", ["ET"], "Neurological", "D"),
  e("Dystonia", [], "Neurological", "D"),
  e("Bell Palsy", ["facial palsy"], "Neurological", "I"),
  e("Trigeminal Neuralgia", ["tic douloureux"], "Neurological", "D"),
  e("Peripheral Neuropathy", [], "Neurological", "D"),
  e("Diabetic Neuropathy", [], "Neurological", "E"),
  e("Complex Regional Pain Syndrome", ["CRPS", "RSD"], "Neurological", "T"),
  e("Idiopathic Intracranial Hypertension", ["IIH", "pseudotumor cerebri"], "Neurological", "V"),
  e("Normal Pressure Hydrocephalus", ["NPH"], "Neurological", "D"),
  e("Brain Abscess", [], "Neurological", "I"),
  e("Encephalitis", [], "Neurological", "I"),
  e("Herpes Simplex Encephalitis", ["HSE"], "Neurological", "I"),
  e("Spinal Cord Injury", ["SCI"], "Neurological", "T"),
  e("Syringomyelia", [], "Neurological", "C"),
  e("Chiari Malformation", [], "Neurological", "C"),
  e("Cerebral Venous Thrombosis", ["CVT"], "Neurological", "V"),
  e("Glioblastoma", ["GBM"], "Neurological", "N"),
  e("Meningioma", [], "Neurological", "N"),
  e("Acoustic Neuroma", ["vestibular schwannoma"], "Neurological", "N"),
  e("Pituitary Adenoma", [], "Neurological", "N"),
  e("Craniopharyngioma", [], "Neurological", "N"),
  e("Narcolepsy", [], "Neurological", "D"),
  e("Restless Legs Syndrome", ["RLS"], "Neurological", "D"),
  e("Wernicke Encephalopathy", ["Wernicke's"], "Neurological", "E"),
  e("Korsakoff Syndrome", [], "Neurological", "E"),
  e("Hepatic Encephalopathy", [], "Neurological", "E"),
  e("Delirium", ["acute confusional state"], "Neurological", "I2"),
  e("Neuroleptic Malignant Syndrome", ["NMS"], "Neurological", "I2"),
  e("Serotonin Syndrome", [], "Neurological", "I2"),
  e("Malignant Hyperthermia", ["MH"], "Neurological", "I2"),
  e("Brown-Sequard Syndrome", [], "Neurological", "T"),
  e("Central Cord Syndrome", [], "Neurological", "T"),
  e("Benign Paroxysmal Positional Vertigo", ["BPPV"], "Neurological", "D"),
  e("Vestibular Neuritis", [], "Neurological", "I"),
  e("Posterior Reversible Encephalopathy Syndrome", ["PRES"], "Neurological", "V"),
  e("Progressive Multifocal Leukoencephalopathy", ["PML"], "Neurological", "I"),
  e("Intraventricular Hemorrhage", ["IVH"], "Neurological", "V"),
  e("Multiple System Atrophy", ["MSA"], "Neurological", "D"),
  e("Complex Partial Seizure", ["focal seizure"], "Neurological", "V"),
  e("Glossopharyngeal Neuralgia", [], "Neurological", "D"),
  e("CNS Lymphoma", [], "Neurological", "N"),

  // ===== RENAL/GU =====
  e("Urinary Tract Infection", ["UTI"], "Renal/GU", "I"),
  e("Pyelonephritis", ["pyelo"], "Renal/GU", "I"),
  e("Nephrolithiasis", ["kidney stone", "renal colic", "kidney stones"], "Renal/GU", "E"),
  e("Acute Kidney Injury", ["AKI", "renal failure"], "Renal/GU", "V"),
  e("Testicular Torsion", [], "Renal/GU", "V"),
  e("Chronic Kidney Disease", ["CKD", "chronic kidney failure"], "Renal/GU", "D"),
  e("Glomerulonephritis", ["GN"], "Renal/GU", "A"),
  e("IgA Nephropathy", ["Berger disease"], "Renal/GU", "A"),
  e("Membranous Nephropathy", [], "Renal/GU", "A"),
  e("Minimal Change Disease", ["MCD"], "Renal/GU", "A"),
  e("Focal Segmental Glomerulosclerosis", ["FSGS"], "Renal/GU", "D"),
  e("Lupus Nephritis", [], "Renal/GU", "A"),
  e("Polycystic Kidney Disease", ["PKD", "ADPKD"], "Renal/GU", "C"),
  e("Renal Cell Carcinoma", ["RCC", "kidney cancer"], "Renal/GU", "N"),
  e("Bladder Cancer", ["transitional cell carcinoma"], "Renal/GU", "N"),
  e("Prostate Cancer", [], "Renal/GU", "N"),
  e("Benign Prostatic Hyperplasia", ["BPH"], "Renal/GU", "D"),
  e("Prostatitis", [], "Renal/GU", "I"),
  e("Epididymitis", [], "Renal/GU", "I"),
  e("Orchitis", [], "Renal/GU", "I"),
  e("Hydrocele", [], "Renal/GU", "C"),
  e("Varicocele", [], "Renal/GU", "V"),
  e("Renal Artery Stenosis", ["RAS"], "Renal/GU", "V"),
  e("Renal Vein Thrombosis", [], "Renal/GU", "V"),
  e("Nephrotic Syndrome", [], "Renal/GU", "A"),
  e("Nephritic Syndrome", [], "Renal/GU", "A"),
  e("Contrast-Induced Nephropathy", ["CIN"], "Renal/GU", "I2"),
  e("Interstitial Nephritis", ["acute interstitial nephritis", "AIN"], "Renal/GU", "I2"),
  e("Urethritis", [], "Renal/GU", "I"),
  e("Cystitis", [], "Renal/GU", "I"),
  e("Urinary Retention", [], "Renal/GU", "D"),
  e("Hydronephrosis", [], "Renal/GU", "V"),
  e("Renal Tubular Acidosis", ["RTA"], "Renal/GU", "C"),
  e("Diabetes Insipidus", ["DI"], "Renal/GU", "E"),
  e("SIADH", ["syndrome of inappropriate ADH"], "Renal/GU", "E"),
  e("Hyperkalemia", ["high potassium"], "Renal/GU", "E"),
  e("Hypokalemia", ["low potassium"], "Renal/GU", "E"),
  e("Hypernatremia", ["high sodium"], "Renal/GU", "E"),
  e("Hyponatremia", ["low sodium"], "Renal/GU", "E"),
  e("Interstitial Cystitis", ["IC", "bladder pain syndrome"], "Renal/GU", "A"),
  e("Medullary Sponge Kidney", [], "Renal/GU", "C"),

  // ===== OB/GYN =====
  e("Ectopic Pregnancy", ["ectopic"], "OB/GYN", "V"),
  e("Ovarian Torsion", ["torsion"], "OB/GYN", "V"),
  e("Placenta Previa", [], "OB/GYN", "V"),
  e("Placental Abruption", ["abruption"], "OB/GYN", "V"),
  e("Preeclampsia", ["pre-eclampsia"], "OB/GYN", "V"),
  e("Eclampsia", [], "OB/GYN", "V"),
  e("HELLP Syndrome", ["HELLP"], "OB/GYN", "V"),
  e("Gestational Diabetes", ["GDM"], "OB/GYN", "E"),
  e("Hyperemesis Gravidarum", ["HG"], "OB/GYN", "E"),
  e("Miscarriage", ["spontaneous abortion"], "OB/GYN", "V"),
  e("Molar Pregnancy", ["hydatidiform mole"], "OB/GYN", "N"),
  e("Endometriosis", [], "OB/GYN", "A"),
  e("Uterine Fibroids", ["leiomyoma", "myoma"], "OB/GYN", "N"),
  e("Polycystic Ovary Syndrome", ["PCOS"], "OB/GYN", "E"),
  e("Ovarian Cyst", [], "OB/GYN", "D"),
  e("Ruptured Ovarian Cyst", [], "OB/GYN", "V"),
  e("Cervical Cancer", [], "OB/GYN", "N"),
  e("Endometrial Cancer", [], "OB/GYN", "N"),
  e("Ovarian Cancer", [], "OB/GYN", "N"),
  e("Pelvic Inflammatory Disease", ["PID"], "OB/GYN", "I"),
  e("Vulvovaginal Candidiasis", ["yeast infection"], "OB/GYN", "I"),
  e("Bacterial Vaginosis", ["BV"], "OB/GYN", "I"),
  e("Bartholin Cyst", ["Bartholin abscess"], "OB/GYN", "I"),
  e("Postpartum Hemorrhage", ["PPH"], "OB/GYN", "V"),
  e("Amniotic Fluid Embolism", ["AFE"], "OB/GYN", "V"),
  e("Preterm Labor", ["PTL"], "OB/GYN", "V"),
  e("Chorioamnionitis", [], "OB/GYN", "I"),
  e("Endometritis", [], "OB/GYN", "I"),
  e("Lichen Sclerosus", [], "OB/GYN", "A"),
  e("Granulosa Cell Tumor", [], "OB/GYN", "N"),

  // ===== INFECTIOUS DISEASE =====
  e("Sepsis", [], "Infectious Disease", "I"),
  e("Endocarditis", ["IE", "infective endocarditis"], "Infectious Disease", "I"),
  e("Osteomyelitis", ["osteo"], "Infectious Disease", "I"),
  e("Cellulitis", [], "Infectious Disease", "I"),
  e("Abscess", [], "Infectious Disease", "I"),
  e("HIV/AIDS", ["HIV", "AIDS"], "Infectious Disease", "I"),
  e("Mononucleosis", ["mono", "EBV", "kissing disease"], "Infectious Disease", "I"),
  e("Influenza", ["flu"], "Infectious Disease", "I"),
  e("COVID-19", ["SARS-CoV-2", "coronavirus"], "Infectious Disease", "I"),
  e("Malaria", [], "Infectious Disease", "I"),
  e("Dengue Fever", ["dengue"], "Infectious Disease", "I"),
  e("Lyme Disease", ["Borrelia"], "Infectious Disease", "I"),
  e("Rocky Mountain Spotted Fever", ["RMSF"], "Infectious Disease", "I"),
  e("Toxoplasmosis", ["toxo"], "Infectious Disease", "I"),
  e("Herpes Simplex", ["HSV", "HSV-1", "HSV-2"], "Infectious Disease", "I"),
  e("Herpes Zoster", ["shingles", "VZV reactivation"], "Infectious Disease", "I"),
  e("Cytomegalovirus", ["CMV"], "Infectious Disease", "I"),
  e("Measles", ["rubeola"], "Infectious Disease", "I"),
  e("Mumps", [], "Infectious Disease", "I"),
  e("Rubella", ["German measles"], "Infectious Disease", "I"),
  e("Tetanus", ["lockjaw"], "Infectious Disease", "I"),
  e("Botulism", [], "Infectious Disease", "I"),
  e("Typhoid Fever", ["Salmonella typhi"], "Infectious Disease", "I"),
  e("Cholera", [], "Infectious Disease", "I"),
  e("Salmonellosis", ["Salmonella"], "Infectious Disease", "I"),
  e("Shigellosis", ["Shigella"], "Infectious Disease", "I"),
  e("Candidiasis", ["thrush", "yeast"], "Infectious Disease", "I"),
  e("Mucormycosis", ["zygomycosis"], "Infectious Disease", "I"),
  e("Coccidioidomycosis", ["valley fever", "cocci"], "Infectious Disease", "I"),
  e("Histoplasmosis", ["histo"], "Infectious Disease", "I"),
  e("Blastomycosis", [], "Infectious Disease", "I"),
  e("Cryptococcal Meningitis", ["crypto meningitis"], "Infectious Disease", "I"),
  e("Necrotizing Fasciitis", ["flesh-eating disease"], "Infectious Disease", "I"),
  e("Gas Gangrene", ["clostridial myonecrosis"], "Infectious Disease", "I"),
  e("Toxic Shock Syndrome", ["TSS"], "Infectious Disease", "I"),
  e("Scarlet Fever", [], "Infectious Disease", "I"),
  e("Rheumatic Fever", ["ARF"], "Infectious Disease", "I"),
  e("Syphilis", [], "Infectious Disease", "I"),
  e("Leptospirosis", [], "Infectious Disease", "I"),
  e("Nocardiosis", [], "Infectious Disease", "I"),
  e("Actinomycosis", [], "Infectious Disease", "I"),
  e("Listeriosis", [], "Infectious Disease", "I"),
  e("Disseminated Gonococcal Infection", ["DGI"], "Infectious Disease", "I"),
  e("Erythema Infectiosum", ["fifth disease", "parvovirus B19"], "Infectious Disease", "I"),
  e("Roseola Infantum", ["HHV-6"], "Infectious Disease", "I"),
  e("Chickenpox", ["varicella"], "Infectious Disease", "I"),
  e("Cryptococcal Infection", ["cryptococcosis"], "Infectious Disease", "I"),

  // ===== ENDOCRINE/METABOLIC =====
  e("Diabetic Ketoacidosis", ["DKA"], "Endocrine/Metabolic", "E"),
  e("Hypoglycemia", ["low blood sugar"], "Endocrine/Metabolic", "E"),
  e("Thyrotoxicosis", ["thyroid storm", "hyperthyroid"], "Endocrine/Metabolic", "E"),
  e("Hypothyroidism", [], "Endocrine/Metabolic", "E"),
  e("Adrenal Insufficiency", ["adrenal crisis"], "Endocrine/Metabolic", "E"),
  e("Type 1 Diabetes", ["T1DM", "insulin-dependent"], "Endocrine/Metabolic", "A"),
  e("Type 2 Diabetes", ["T2DM", "non-insulin-dependent"], "Endocrine/Metabolic", "E"),
  e("Hyperthyroidism", [], "Endocrine/Metabolic", "E"),
  e("Graves Disease", ["Graves'"], "Endocrine/Metabolic", "A"),
  e("Hashimoto Thyroiditis", ["Hashimoto's"], "Endocrine/Metabolic", "A"),
  e("Thyroid Nodule", [], "Endocrine/Metabolic", "N"),
  e("Thyroid Cancer", ["papillary thyroid", "follicular thyroid"], "Endocrine/Metabolic", "N"),
  e("Subacute Thyroiditis", ["de Quervain thyroiditis"], "Endocrine/Metabolic", "I"),
  e("Cushing Syndrome", ["Cushing's", "hypercortisolism"], "Endocrine/Metabolic", "E"),
  e("Addison Disease", ["Addison's", "primary adrenal insufficiency"], "Endocrine/Metabolic", "A"),
  e("Pheochromocytoma", ["pheo"], "Endocrine/Metabolic", "N"),
  e("Hyperaldosteronism", ["Conn syndrome", "primary aldosteronism"], "Endocrine/Metabolic", "E"),
  e("Primary Hyperparathyroidism", ["PHPT"], "Endocrine/Metabolic", "E"),
  e("Hypoparathyroidism", [], "Endocrine/Metabolic", "E"),
  e("Hypercalcemia", ["high calcium"], "Endocrine/Metabolic", "E"),
  e("Hypocalcemia", ["low calcium"], "Endocrine/Metabolic", "E"),
  e("Acromegaly", [], "Endocrine/Metabolic", "N"),
  e("Prolactinoma", [], "Endocrine/Metabolic", "N"),
  e("Metabolic Syndrome", ["syndrome X"], "Endocrine/Metabolic", "E"),
  e("Phenylketonuria", ["PKU"], "Endocrine/Metabolic", "C"),
  e("Familial Hypercholesterolemia", [], "Endocrine/Metabolic", "C"),
  e("Carcinoid Syndrome", [], "Endocrine/Metabolic", "N"),
  e("Multiple Endocrine Neoplasia", ["MEN", "MEN1", "MEN2"], "Endocrine/Metabolic", "C"),
  e("Vitamin D Deficiency", [], "Endocrine/Metabolic", "E"),
  e("Vitamin B12 Deficiency", ["B12 deficiency"], "Endocrine/Metabolic", "E"),
  e("Iron Deficiency", [], "Endocrine/Metabolic", "E"),
  e("Folate Deficiency", ["folic acid deficiency"], "Endocrine/Metabolic", "E"),
  e("Refeeding Syndrome", [], "Endocrine/Metabolic", "E"),
  e("Tumor Lysis Syndrome", ["TLS"], "Endocrine/Metabolic", "I2"),
  e("Pellagra", ["niacin deficiency"], "Endocrine/Metabolic", "E"),
  e("Eruptive Xanthomas", [], "Endocrine/Metabolic", "E"),
  e("Necrobiosis Lipoidica", [], "Endocrine/Metabolic", "E"),

  // ===== HEMATOLOGIC/ONCOLOGIC =====
  e("Lymphoma", [], "Hematologic/Oncologic", "N"),
  e("Iron Deficiency Anemia", ["IDA"], "Hematologic/Oncologic", "E"),
  e("B12 Deficiency Anemia", ["pernicious anemia"], "Hematologic/Oncologic", "E"),
  e("Folate Deficiency Anemia", [], "Hematologic/Oncologic", "E"),
  e("Anemia of Chronic Disease", ["ACD"], "Hematologic/Oncologic", "D"),
  e("Sickle Cell Disease", ["SCD", "sickle cell anemia"], "Hematologic/Oncologic", "C"),
  e("Thalassemia", ["thal"], "Hematologic/Oncologic", "C"),
  e("G6PD Deficiency", ["glucose-6-phosphate dehydrogenase deficiency"], "Hematologic/Oncologic", "C"),
  e("Hereditary Spherocytosis", ["HS"], "Hematologic/Oncologic", "C"),
  e("Autoimmune Hemolytic Anemia", ["AIHA"], "Hematologic/Oncologic", "A"),
  e("Thrombotic Thrombocytopenic Purpura", ["TTP"], "Hematologic/Oncologic", "A"),
  e("Hemolytic Uremic Syndrome", ["HUS"], "Hematologic/Oncologic", "I"),
  e("Disseminated Intravascular Coagulation", ["DIC"], "Hematologic/Oncologic", "V"),
  e("Immune Thrombocytopenic Purpura", ["ITP"], "Hematologic/Oncologic", "A"),
  e("Von Willebrand Disease", ["VWD"], "Hematologic/Oncologic", "C"),
  e("Hemophilia A", ["factor VIII deficiency"], "Hematologic/Oncologic", "C"),
  e("Hemophilia B", ["factor IX deficiency", "Christmas disease"], "Hematologic/Oncologic", "C"),
  e("Factor V Leiden", ["FVL"], "Hematologic/Oncologic", "C"),
  e("Antiphospholipid Syndrome", ["APS", "APLA"], "Hematologic/Oncologic", "A"),
  e("Heparin-Induced Thrombocytopenia", ["HIT"], "Hematologic/Oncologic", "I2"),
  e("Polycythemia Vera", ["PV"], "Hematologic/Oncologic", "N"),
  e("Essential Thrombocythemia", ["ET"], "Hematologic/Oncologic", "N"),
  e("Myelofibrosis", ["MF"], "Hematologic/Oncologic", "N"),
  e("Chronic Myeloid Leukemia", ["CML"], "Hematologic/Oncologic", "N"),
  e("Acute Myeloid Leukemia", ["AML"], "Hematologic/Oncologic", "N"),
  e("Acute Lymphoblastic Leukemia", ["ALL"], "Hematologic/Oncologic", "N"),
  e("Chronic Lymphocytic Leukemia", ["CLL"], "Hematologic/Oncologic", "N"),
  e("Hodgkin Lymphoma", ["HL", "Hodgkin disease"], "Hematologic/Oncologic", "N"),
  e("Non-Hodgkin Lymphoma", ["NHL"], "Hematologic/Oncologic", "N"),
  e("Diffuse Large B-Cell Lymphoma", ["DLBCL"], "Hematologic/Oncologic", "N"),
  e("Multiple Myeloma", ["MM"], "Hematologic/Oncologic", "N"),
  e("Waldenstrom Macroglobulinemia", [], "Hematologic/Oncologic", "N"),
  e("Myelodysplastic Syndrome", ["MDS"], "Hematologic/Oncologic", "N"),
  e("Aplastic Anemia", ["AA"], "Hematologic/Oncologic", "A"),
  e("Febrile Neutropenia", [], "Hematologic/Oncologic", "I"),
  e("Paraneoplastic Syndrome", [], "Hematologic/Oncologic", "N"),
  e("Cold Agglutinin Syndrome", [], "Hematologic/Oncologic", "A"),
  e("Intravascular Lymphoma", [], "Hematologic/Oncologic", "N"),
  e("Kaposi's Sarcoma", ["KS"], "Hematologic/Oncologic", "N"),
  e("Hemophilia", [], "Hematologic/Oncologic", "C"),

  // ===== DERMATOLOGIC =====
  e("Contact Dermatitis", ["allergic contact dermatitis"], "Dermatologic", "A"),
  e("Atopic Dermatitis", ["eczema"], "Dermatologic", "A"),
  e("Psoriasis", [], "Dermatologic", "A"),
  e("Urticaria", ["hives"], "Dermatologic", "A"),
  e("Angioedema", [], "Dermatologic", "A"),
  e("Erythema Multiforme", ["EM"], "Dermatologic", "A"),
  e("Stevens-Johnson Syndrome", ["SJS"], "Dermatologic", "I2"),
  e("Toxic Epidermal Necrolysis", ["TEN"], "Dermatologic", "I2"),
  e("Pemphigus Vulgaris", [], "Dermatologic", "A"),
  e("Bullous Pemphigoid", [], "Dermatologic", "A"),
  e("Dermatitis Herpetiformis", ["DH"], "Dermatologic", "A"),
  e("Acne Vulgaris", ["acne"], "Dermatologic", "I"),
  e("Rosacea", [], "Dermatologic", "D"),
  e("Seborrheic Dermatitis", [], "Dermatologic", "D"),
  e("Tinea Corporis", ["ringworm"], "Dermatologic", "I"),
  e("Tinea Pedis", ["athlete's foot"], "Dermatologic", "I"),
  e("Tinea Capitis", [], "Dermatologic", "I"),
  e("Tinea Versicolor", ["pityriasis versicolor"], "Dermatologic", "I"),
  e("Tinea Cruris", ["jock itch"], "Dermatologic", "I"),
  e("Onychomycosis", ["nail fungus"], "Dermatologic", "I"),
  e("Scabies", [], "Dermatologic", "I"),
  e("Impetigo", [], "Dermatologic", "I"),
  e("Folliculitis", [], "Dermatologic", "I"),
  e("Erysipelas", [], "Dermatologic", "I"),
  e("Basal Cell Carcinoma", ["BCC"], "Dermatologic", "N"),
  e("Squamous Cell Carcinoma", ["SCC"], "Dermatologic", "N"),
  e("Malignant Melanoma", ["melanoma"], "Dermatologic", "N"),
  e("Actinic Keratosis", ["AK", "solar keratosis"], "Dermatologic", "N"),
  e("Seborrheic Keratosis", ["SK"], "Dermatologic", "D"),
  e("Dermatofibroma", [], "Dermatologic", "D"),
  e("Lipoma", [], "Dermatologic", "N"),
  e("Pyoderma Gangrenosum", [], "Dermatologic", "A"),
  e("Erythema Nodosum", ["EN"], "Dermatologic", "A"),
  e("Vitiligo", [], "Dermatologic", "A"),
  e("Alopecia Areata", [], "Dermatologic", "A"),
  e("Lichen Planus", [], "Dermatologic", "A"),
  e("Pityriasis Rosea", [], "Dermatologic", "I"),
  e("Drug Eruption", ["drug rash"], "Dermatologic", "I2"),
  e("Molluscum Contagiosum", [], "Dermatologic", "I"),
  e("Bowen's Disease", [], "Dermatologic", "N"),
  e("Keratoacanthoma", [], "Dermatologic", "N"),
  e("Porphyria Cutanea Tarda", ["PCT"], "Dermatologic", "E"),
  e("Erythema Ab Igne", [], "Dermatologic", "T"),
  e("Exogenous Ochronosis", [], "Dermatologic", "I2"),
  e("Drug Reaction", ["adverse drug reaction", "ADR"], "Dermatologic", "I2"),
  e("Eczematous Dermatitis", ["eczema"], "Dermatologic", "A"),
  e("Livedo Reticularis", [], "Dermatologic", "V"),
  e("Drug Reaction with Eosinophilia and Systemic Symptoms", ["DRESS syndrome"], "Dermatologic", "I2"),
  e("Pyogenic Granuloma", [], "Dermatologic", "V"),

  // ===== PSYCHIATRIC =====
  e("Anxiety / Panic Attack", ["panic", "anxiety", "panic attack"], "Psychiatric", "D"),
  e("Major Depressive Disorder", ["MDD", "depression"], "Psychiatric", "D"),
  e("Bipolar I Disorder", ["bipolar", "manic depression"], "Psychiatric", "D"),
  e("Bipolar II Disorder", [], "Psychiatric", "D"),
  e("Generalized Anxiety Disorder", ["GAD"], "Psychiatric", "D"),
  e("Social Anxiety Disorder", ["social phobia"], "Psychiatric", "D"),
  e("Panic Disorder", [], "Psychiatric", "D"),
  e("Obsessive-Compulsive Disorder", ["OCD"], "Psychiatric", "D"),
  e("Post-Traumatic Stress Disorder", ["PTSD"], "Psychiatric", "T"),
  e("Acute Stress Disorder", ["ASD"], "Psychiatric", "T"),
  e("Adjustment Disorder", [], "Psychiatric", "D"),
  e("Schizophrenia", [], "Psychiatric", "D"),
  e("Schizoaffective Disorder", [], "Psychiatric", "D"),
  e("Brief Psychotic Disorder", [], "Psychiatric", "D"),
  e("Delusional Disorder", [], "Psychiatric", "D"),
  e("Substance Use Disorder", ["SUD"], "Psychiatric", "I2"),
  e("Alcohol Use Disorder", ["AUD", "alcoholism"], "Psychiatric", "I2"),
  e("Opioid Use Disorder", ["OUD"], "Psychiatric", "I2"),
  e("Alcohol Withdrawal", [], "Psychiatric", "I2"),
  e("Delirium Tremens", ["DTs"], "Psychiatric", "I2"),
  e("Anorexia Nervosa", ["anorexia"], "Psychiatric", "D"),
  e("Bulimia Nervosa", ["bulimia"], "Psychiatric", "D"),
  e("Binge Eating Disorder", ["BED"], "Psychiatric", "D"),
  e("Somatic Symptom Disorder", ["somatization"], "Psychiatric", "D"),
  e("Conversion Disorder", ["functional neurological disorder"], "Psychiatric", "D"),
  e("Factitious Disorder", ["Munchausen"], "Psychiatric", "D"),
  e("ADHD", ["attention deficit hyperactivity disorder"], "Psychiatric", "D"),
  e("Autism Spectrum Disorder", ["ASD", "autism"], "Psychiatric", "C"),
  e("Oppositional Defiant Disorder", ["ODD"], "Psychiatric", "D"),
  e("Borderline Personality Disorder", ["BPD"], "Psychiatric", "D"),
  e("Somatization Disorder", [], "Psychiatric", "D"),
  e("Situational Syncope", [], "Psychiatric", "D"),

  // ===== RHEUMATOLOGIC =====
  e("Systemic Lupus Erythematosus", ["SLE", "lupus"], "Rheumatologic", "A"),
  e("Sjogren Syndrome", ["Sjogren's"], "Rheumatologic", "A"),
  e("Systemic Sclerosis", ["scleroderma", "SSc"], "Rheumatologic", "A"),
  e("Dermatomyositis", [], "Rheumatologic", "A"),
  e("Polymyositis", [], "Rheumatologic", "A"),
  e("Mixed Connective Tissue Disease", ["MCTD"], "Rheumatologic", "A"),
  e("Polyarteritis Nodosa", ["PAN"], "Rheumatologic", "A"),
  e("Granulomatosis with Polyangiitis", ["GPA", "Wegener's"], "Rheumatologic", "A"),
  e("Eosinophilic Granulomatosis with Polyangiitis", ["EGPA", "Churg-Strauss"], "Rheumatologic", "A"),
  e("Microscopic Polyangiitis", ["MPA"], "Rheumatologic", "A"),
  e("Giant Cell Arteritis", ["GCA", "temporal arteritis"], "Rheumatologic", "A"),
  e("Takayasu Arteritis", [], "Rheumatologic", "A"),
  e("Henoch-Schonlein Purpura", ["HSP", "IgA vasculitis"], "Rheumatologic", "A"),
  e("Behcet Disease", ["Behcet's"], "Rheumatologic", "A"),
  e("Reactive Arthritis", ["Reiter's syndrome"], "Rheumatologic", "A"),
  e("Psoriatic Arthritis", ["PsA"], "Rheumatologic", "A"),
  e("Juvenile Idiopathic Arthritis", ["JIA", "JRA"], "Rheumatologic", "A"),
  e("Adult-Onset Still Disease", ["AOSD"], "Rheumatologic", "A"),
  e("Relapsing Polychondritis", [], "Rheumatologic", "A"),
  e("IgG4-Related Disease", ["IgG4-RD"], "Rheumatologic", "A"),
  e("Sarcoidosis", [], "Rheumatologic", "A"),
  e("Amyloidosis", [], "Rheumatologic", "D"),
  e("Cryoglobulinemic Vasculitis", ["cryoglobulinemia"], "Rheumatologic", "A"),
  e("Diffuse Cutaneous Systemic Sclerosis", ["scleroderma"], "Rheumatologic", "A"),
  e("Eosinophilic Fasciitis", [], "Rheumatologic", "A"),

  // ===== ENT =====
  e("Otitis Media", ["OM", "ear infection"], "ENT", "I"),
  e("Otitis Externa", ["swimmer's ear"], "ENT", "I"),
  e("Sinusitis", ["rhinosinusitis"], "ENT", "I"),
  e("Pharyngitis", ["sore throat"], "ENT", "I"),
  e("Streptococcal Pharyngitis", ["strep throat", "GAS pharyngitis"], "ENT", "I"),
  e("Peritonsillar Abscess", ["PTA", "quinsy"], "ENT", "I"),
  e("Retropharyngeal Abscess", [], "ENT", "I"),
  e("Laryngitis", [], "ENT", "I"),
  e("Vocal Cord Paralysis", [], "ENT", "D"),
  e("Meniere Disease", ["Meniere's"], "ENT", "D"),
  e("Sudden Sensorineural Hearing Loss", ["SSNHL"], "ENT", "V"),
  e("Epistaxis", ["nosebleed"], "ENT", "V"),
  e("Nasal Polyps", [], "ENT", "A"),
  e("Allergic Rhinitis", ["hay fever"], "ENT", "A"),
  e("Salivary Gland Stone", ["sialolithiasis"], "ENT", "E"),
  e("Parotitis", [], "ENT", "I"),
  e("Ludwig Angina", ["submandibular space infection"], "ENT", "I"),
  e("Laryngeal Candidiasis", [], "ENT", "I"),
  e("Temporomandibular Joint Dysfunction", ["TMJ", "TMD"], "ENT", "D"),

  // ===== OPHTHALMOLOGIC =====
  e("Conjunctivitis", ["pink eye"], "Ophthalmologic", "I"),
  e("Corneal Abrasion", [], "Ophthalmologic", "T"),
  e("Corneal Ulcer", [], "Ophthalmologic", "I"),
  e("Uveitis", ["iritis"], "Ophthalmologic", "A"),
  e("Acute Angle-Closure Glaucoma", ["AACG", "closed-angle glaucoma"], "Ophthalmologic", "V"),
  e("Open-Angle Glaucoma", ["OAG", "POAG"], "Ophthalmologic", "D"),
  e("Retinal Detachment", ["RD"], "Ophthalmologic", "V"),
  e("Central Retinal Artery Occlusion", ["CRAO"], "Ophthalmologic", "V"),
  e("Central Retinal Vein Occlusion", ["CRVO"], "Ophthalmologic", "V"),
  e("Macular Degeneration", ["AMD", "ARMD"], "Ophthalmologic", "D"),
  e("Diabetic Retinopathy", ["DR"], "Ophthalmologic", "E"),
  e("Hypertensive Retinopathy", [], "Ophthalmologic", "V"),
  e("Optic Neuritis", [], "Ophthalmologic", "A"),
  e("Papilledema", [], "Ophthalmologic", "V"),
  e("Orbital Cellulitis", [], "Ophthalmologic", "I"),
  e("Preseptal Cellulitis", ["periorbital cellulitis"], "Ophthalmologic", "I"),
  e("Endophthalmitis", [], "Ophthalmologic", "I"),
  e("Cytomegalovirus Retinitis", ["CMV retinitis"], "Ophthalmologic", "I"),
  e("Keratoconus", [], "Ophthalmologic", "D"),
  e("Subconjunctival Hemorrhage", [], "Ophthalmologic", "V"),

  // ===== TOXICOLOGY =====
  e("Acetaminophen Overdose", ["Tylenol overdose", "APAP toxicity"], "Toxicology", "I2"),
  e("Aspirin Toxicity", ["salicylate poisoning"], "Toxicology", "I2"),
  e("Opioid Overdose", ["narcotic overdose"], "Toxicology", "I2"),
  e("Benzodiazepine Overdose", ["benzo OD"], "Toxicology", "I2"),
  e("Tricyclic Antidepressant Overdose", ["TCA overdose"], "Toxicology", "I2"),
  e("Beta-Blocker Overdose", [], "Toxicology", "I2"),
  e("Calcium Channel Blocker Overdose", ["CCB overdose"], "Toxicology", "I2"),
  e("Digoxin Toxicity", [], "Toxicology", "I2"),
  e("Lithium Toxicity", [], "Toxicology", "I2"),
  e("Carbon Monoxide Poisoning", ["CO poisoning"], "Toxicology", "I2"),
  e("Cyanide Poisoning", [], "Toxicology", "I2"),
  e("Organophosphate Poisoning", ["OP poisoning"], "Toxicology", "I2"),
  e("Methanol Poisoning", [], "Toxicology", "I2"),
  e("Ethylene Glycol Poisoning", [], "Toxicology", "I2"),
  e("Lead Poisoning", ["plumbism"], "Toxicology", "I2"),
  e("Iron Poisoning", [], "Toxicology", "I2"),
  e("Anticholinergic Toxicity", [], "Toxicology", "I2"),
  e("Sympathomimetic Toxicity", [], "Toxicology", "I2"),
  e("Akathisia", [], "Toxicology", "I2"),

  // ===== GENERAL/CONSTITUTIONAL =====
  e("Anaphylaxis", [], "General/Constitutional", "A"),
  e("Dehydration", [], "General/Constitutional", "E"),
  e("Heat Stroke", ["heat exhaustion"], "General/Constitutional", "T"),
  e("Hypothermia", [], "General/Constitutional", "T"),
  e("Syncope", ["fainting"], "General/Constitutional", "V"),
  e("Chronic Fatigue Syndrome", ["CFS", "ME/CFS"], "General/Constitutional", "D"),
  e("Fever of Unknown Origin", ["FUO"], "General/Constitutional", "I"),
  e("Failure to Thrive", ["FTT"], "General/Constitutional", "E"),
];

// Deduplicate by lowercase term
const seen = new Set<string>();
const deduped: Entry[] = [];
for (const entry of entries) {
  const key = entry.term.toLowerCase();
  if (!seen.has(key)) {
    seen.add(key);
    deduped.push(entry);
  }
}

// Sort alphabetically
deduped.sort((a, b) => a.term.localeCompare(b.term));

const output = JSON.stringify(deduped, null, 2);
const outputPath = path.join(__dirname, "../src/data/clinical-vocabulary.json");
fs.writeFileSync(outputPath, output);
console.log(`Wrote ${deduped.length} entries to ${outputPath}`);
